export { default as Connect } from './Connect'
export { default as Header } from './Header'
export { default as Projects } from './Projects'
export { default as Skills } from './Skills'
export { default as About } from './About'
export { default as Langs } from './Languages'